fix(security): Fix the issue of missing device-modbus's Kong route
edgexfoundry/edgex-compose pull request #101
Opened 2021-05-21 21:56 UTC by jim-wang-intel

Fix the missing Kong route of `device-modbus` on TAF test using env `ADD_PROXY_ROUTE` of `proxy-setup`

Fixes: #100

Signed-off-by: Jim Wang <yutsung.jim.wang@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## What is the current behavior?

kong route seems to be missing based on the error log of TAF testing on `device-modbus` through Kong.

## Issue Number:  #100 

## What is the new behavior?
Added kong route through env `ADD_PROXY_ROUTE` for device-modbus.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

## New Imports
Are there any new imports or modules? If so, what are they used for and why?

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2021-05-21 22:11 UTC, lenny-intel requested changes
This addresses the one TAF issue, but need to solve for all add on services. Looks like you have the template updated, but not setting EXTRA_PROXY_ROUTE_LIST like we do with the others for each add on service option.
i.e. need a section like this for each add on service:
```
		ifeq ($(EXTRA_PROXY_ROUTE_LIST),"")
			EXTRA_PROXY_ROUTE_LIST:=<service-key>.http://<hostname>:<port>
		else
			EXTRA_PROXY_ROUTE_LIST:=<service-key>.http://<hostname>:<port>
		endif
```

Then the question is does TAF need this for all the add on services or just Device Modbus. @cherrycl ?

2021-05-21 22:20 UTC, jim-wang-intel commented
> This addresses the one TAF issue, but need to solve for all add on services. Looks like you have the template updated, but not setting EXTRA_PROXY_ROUTE_LIST like we do with the others for each add on service option.

This issue is NOT clear to me; i.e., its coming from TAF test failure. So with adding the newly add-on seems to be me an enhancement not a bug because we never had that need or use case until now right?


> i.e. need a section like this for each add on service:
> 
> ```
> 		ifeq ($(EXTRA_PROXY_ROUTE_LIST),"")
> 			EXTRA_PROXY_ROUTE_LIST:=<service-key>.http://<hostname>:<port>
> 		else
> 			EXTRA_PROXY_ROUTE_LIST:=<service-key>.http://<hostname>:<port>
> 		endif
> ```
> 
> Then the question is does TAF need this for all the add on services or just Device Modbus. @cherrycl ?

Yes, that is a good question for @cherrycl to answer.

2021-05-21 22:23 UTC, jim-wang-intel commented on compose-builder/Makefile
> +	EXTRA_PROXY_ROUTE_LIST:=edgex-device-modbus.http://device-modbus:59901
good catch.  so `device-modbus` is service key and `edgex-device-modbus` is considered as service name, correct?

2021-05-21 22:27 UTC, lenny-intel commented on compose-builder/Makefile
> +	EXTRA_PROXY_ROUTE_LIST:=edgex-device-modbus.http://device-modbus:59901
correct. we do have some inconsistency in the names used for the routes in the static config. `coredata` vs `core-data`, etc and `virtualdevice` vs `device-virtual`. For the add ones it should use the service key for the route name and then we can talk about addressing the others later.

2021-05-21 22:48 UTC, lenny-intel commented
> adding the newly add-on seems to be me an enhancement not a bug because we never had that need or use case until now right?
> 

@jim-wang-intel , whichever. I thought we had covered adding the proxies, but apparently not ;-). We can address the TAF issue with this PR and then do a separate PR for the general add on services.

2021-05-21 22:52 UTC, jim-wang-intel commented
> > adding the newly add-on seems to be me an enhancement not a bug because we never had that need or use case until now right?
> 
> @jim-wang-intel , whichever. I thought we had covered adding the proxies, but apparently not ;-). We can address the TAF issue with this PR and then do a separate PR for the general add on services.

Ok, but I guess my question is the need to open all services up to the proxy or gateway. Do we see that as a use case of today of we just try to make it consistent?  These two are totally different perspective to resolve and adding more into route means to increase your attack surfaces in the security point of view.

2021-05-22 03:17 UTC, cloudxxx8 commented
I thought we should not open any Device Service to the proxy by default, but the user should have the capability to add on their own.

2021-05-24 02:33 UTC, cherrycl commented
@jim-wang-intel @lenny-intel Besides the default service that existing in [edgex-proxy-setup](https://github.com/edgexfoundry/edgex-go/blob/dfd83a2c80b22c5abde7548ed5ab1fe11263d6eb/cmd/security-proxy-setup/res/configuration.toml), currently, only needs to add device-modbus to the proxy.  Thank you.

2021-05-24 14:53 UTC, lenny-intel commented
> currently, only needs to add device-modbus to the proxy

@cloudxxx8 , @cherrycl , Ok, thanks for the clarification!

2021-05-24 14:54 UTC, lenny-intel approved these changes
LGTM

2021-05-24 14:55 UTC, merged