refactor: Populate with Compose Builder from developer-scripts
edgexfoundry/edgex-compose pull request #3
Opened 2021-02-17 00:34 UTC by lenny-intel

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## What is the current behavior?
Repo is empty

## Issue Number: #2

## What is the new behavior?
Populated with compose builder and ran build to generate all the `pre-release` compose files.
Following where changed:

- Rename the `nexus/nightly-build` release to `pre-release`
- Drop the `compose-files` sub-folder
- Fix get-token in `releases/pre-release/Makefile`  to call new script in compose-builder folder

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

## New Imports
Are there any new imports or modules? If so, what are they used for and why?
no

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2021-02-17 15:33 UTC, jim-wang-intel requested changes
some minor clean-ups

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/.env
> + #  * Copyright 2020 Intel
change copyright to 2021

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/.env
> +RELEASE_FOLDER=../releases/${RELEASE}
move this up together with `RELEASE`, making it easier to read

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/README.md
> +
Remove extra lines

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/add-device-bacnet.yml
> +#  * Copyright 2020 Intel Corporation.
change to 2021

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/add-asc-http-export-secure.yml
> +version: '3.7'
should we add copyright header?

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/add-asc-http-export.yml
> +version: '3.7'
should we add copyright header?

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/add-asc-mqtt-export-secure.yml
> +version: '3.7'
should we add copyright header?

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/add-asc-mqtt-export.yml
> +version: '3.7'
should we add copyright header?

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/add-device-camera.yml
> +#  * Copyright 2020 Intel Corporation.
2021

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/add-device-grove.yml
> +#  * Copyright 2020 Intel Corporation.
2021

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/add-device-modbus.yml
> +#  * Copyright 2020 Intel Corporation.
2021

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/add-device-mqtt.yml
> +#  * Copyright 2020 Intel Corporation.
2021

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/add-device-random.yml
> +#  * Copyright 2020 Intel Corporation.
2021

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/add-device-rest.yml
> +#  * Copyright 2020 Intel Corporation.
2021

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/add-device-snmp.yml
> +#  * Copyright 2020 Intel Corporation.
2021

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/add-device-virtual.yml
> +#  * Copyright 2020 Intel Corporation.
2021

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/add-modbus-simulator.yml
> +version: '3.7'
copyright header

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/add-mqtt-broker.yml
> +version: '3.7'
copyright header

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/add-mqtt-messagebus.yml
> +#  * Copyright 2020 Intel
2021

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/add-taf-app-services.yml
> +version: '3.7'
copyright header

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/add-taf-device-services-mods.yml
> +version: '3.7'
copyright header

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/common-security.env
> +#  * Copyright 2020 Intel
2021

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/common.env
> +#  * Copyright 2020 Intel
2021

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/docker-compose-base.yml
> +# and Secret Store
the comments about security service is kind of out-of-date; not just api gateway and secret store but also other security services.

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/docker-compose-ui.yml
> +#  * Copyright 2020 Intel Corporation.
2021

2021-02-17 15:33 UTC, jim-wang-intel commented on compose-builder/gen-header
> +# at the top level of the developer-scripts repo.
this comment out-of-date, no longer developer-scripts

2021-02-17 15:33 UTC, jim-wang-intel commented on releases/pre-release/Makefile
> +#  * Copyright 2020 Intel
2021

2021-02-17 15:33 UTC, jim-wang-intel commented on releases/pre-release/docker-compose-portainer.yml
> +#  * Copyright 2020 Intel Corporation.
2021

2021-02-17 15:34 UTC, jim-wang-intel commented on compose-builder/gen-header
> +# DO NOT MAKE CHANGES that are intended to be permanent to EdgeX developer-scripts repo.
out-of-date

2021-02-17 17:22 UTC, jim-wang-intel approved these changes
LGTM

2021-02-18 22:16 UTC, jpwhitemn approved these changes

2021-02-18 22:18 UTC, merged