fix: added missing delayed started spiffe volume for support services
edgexfoundry/edgex-compose pull request #365
Opened 2023-04-11 19:38 UTC by jim-wang-intel

Updated Makefile to run delayed-started generation script for support services to make sure these serivces are delayed-startable

  Fixes: #364

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-compose/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

- docker build the latest edgex-go and ensure the fix in this PR is in there: https://github.com/edgexfoundry/edgex-go/pull/4509 
- use compose_builder to run it with delay-started mode: `make run dev delayed-start ds-virtual ds-modbus` 
- wait for a few minutes to let everything start up and settle down
- verify that both `support-notifications` and `support-scheduler` are now received tokens from spiffe token provider

2023-04-11 19:45 UTC, bnevis-i approved these changes
LGTM

2023-04-11 19:49 UTC, jim-wang-intel commented
@cherrycl please verify on your side too to make sure this works for your testing environment, thanks!

2023-04-11 21:13 UTC, bnevis-i commented
Note that https://github.com/edgexfoundry/edgex-go/pull/4509 needs to be merged before this fix will work.

2023-04-11 21:31 UTC, lenny-intel requested changes
Need to run `make build`

2023-04-11 21:34 UTC, bnevis-i commented
> Need to run `make build`

Let's get this added to the PR checklist.  I am tired of seeing you type it.

2023-04-11 21:34 UTC, jim-wang-intel commented
> Need to run `make build`

no changes, no compose file changes

2023-04-11 21:39 UTC, lenny-intel commented
> no changes, no compose file changes

Then how is this addressing the issue if no compose file changes?

2023-04-11 21:41 UTC, bnevis-i commented
> > no changes, no compose file changes
> 
> Then how is this addressing the issue if no compose file changes?

`delayed-start` is a nonstandard option -- it isn't enabled in the pre-built docker-compose files.

2023-04-11 21:49 UTC, lenny-intel commented
> `delayed-start` is a nonstandard option -- it isn't enabled in the pre-built docker-compose files.

Ohh Yea, for got... ;-)

2023-04-11 21:49 UTC, lenny-intel approved these changes
LGTM

2023-04-11 21:56 UTC, jim-wang-intel commented
> > Need to run `make build`
> 
> Let's get this added to the PR checklist. I am tired of seeing you type it.

Bryon: create a `make build` robot when any PR check in :-)

2023-04-12 08:24 UTC, cherrycl approved these changes
LGTM

2023-04-12 09:11 UTC, merged