feat(security): Update consul's volume on secrets folder to be writable
edgexfoundry/edgex-compose pull request #41
Opened 2021-03-30 23:38 UTC by jim-wang-intel

- mount /tmp/edgex/secrets/ to be writable volume

Closes: #40

Signed-off-by: Jim Wang <yutsung.jim.wang@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## What is the current behavior?

Currently, the /tmp/edgex/secrets/ is not mounted as volume and thus it is read-only as the container itself is read-only system.

## Issue Number: #40 

## What is the new behavior?
Mount the volume `/tmp/edgex/secrets` folder to be writable.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

## New Imports
Are there any new imports or modules? If so, what are they used for and why?

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information
This PR should be merged together with the edgex-go PR  https://github.com/edgexfoundry/edgex-go/pull/3324 so that the token generation process can work properly.

2021-03-30 23:40 UTC, bnevis-i requested changes
Remove 
```
- /tmp/edgex/secrets/edgex-consul:/tmp/edgex/secrets/edgex-consul:ro,z
```

2021-03-30 23:53 UTC, lenny-intel approved these changes
LGTM

2021-03-30 23:54 UTC, bnevis-i approved these changes
LGTM

2021-04-01 16:02 UTC, lenny-intel commented
recheck

2021-04-01 16:28 UTC, merged