feat: Add Device S7 generator script
edgexfoundry/edgex-compose pull request #431
Opened 2024-02-22 00:49 UTC by jiekechoo

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-compose/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

2024-02-22 14:28 UTC, lenny-intel requested changes

2024-02-22 14:28 UTC, lenny-intel commented on compose-builder/add-device-s7.yml
> +    image: ${DEVICE_SVC_REPOSITORY}/device-s7${ARCH}:${DEVICE_MODBUS_VERSION}
Add DEVICE_S7_VERSION to `.env` file
```suggestion
    image: ${DEVICE_SVC_REPOSITORY}/device-s7${ARCH}:${DEVICE_S7_VERSION}
```

2024-02-22 14:50 UTC, jiekechoo commented on compose-builder/add-device-s7.yml
> +    image: ${DEVICE_SVC_REPOSITORY}/device-s7${ARCH}:${DEVICE_MODBUS_VERSION}
Thanks for your help. :D

2024-02-22 15:42 UTC, lenny-intel approved these changes

2024-02-22 15:43 UTC, lenny-intel commented
@jiekechoo , please fix your last commit message (amend) causing the Semantic PR check to fail.

2024-02-24 02:26 UTC, lenny-intel commented
@cherrycl , This PR doesn't impact any smoke tests, but all are failing, Please advise @jiekechoo  on how to resolve it.

2024-02-26 01:00 UTC, cherrycl commented
@jiekechoo Please rebase and squash commits.

2024-02-26 13:34 UTC, closed without merging

2024-02-26 13:35 UTC, jiekechoo commented
Another PR replace this.