feat: update build-canned
edgexfoundry/edgex-compose pull request #443
Opened 2024-03-28 22:44 UTC by dovholuknf

updates compose-builder's `make build-canned`

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

2024-03-29 00:13 UTC, lenny-intel requested changes

2024-03-29 00:13 UTC, lenny-intel commented on compose-builder/Makefile
> +	cat gen-header docker-compose.yml > $(RELEASE_FOLDER)/docker-compose$(NO_SECURITY)$(APP_SAMPLE)$(BUS)$(NANOMQ)$(ARCH)$(ZERO_TRUST_COMPOSE).yml
ARCH needs to always be last. 

```suggestion
	cat gen-header docker-compose.yml > $(RELEASE_FOLDER)/docker-compose$(NO_SECURITY)$(APP_SAMPLE)$(BUS)$(NANOMQ)$(ZERO_TRUST_COMPOSE)$(ARCH).yml
```

2024-03-29 00:54 UTC, lenny-goodell submitted a review, later dismissed
LGTM, putting in draft until @cloudxxx8 and team can agree to the required min version of docker compose.

2024-04-12 18:44 UTC, dovholuknf commented
@cloudxxx8 - I've updated compose builder with the alpha release of ekuiper that contains OpenZiti support. When the actual build is released, we can update again. I've asked about the release date of ekuiper 1.14 here https://github.com/lf-edge/ekuiper/discussions/2772

In a previous core WG meeting we agreed verbally and in the TSC we agreed that the version of docker compose was acceptable. I'm marking this PR as 'ready'

2024-04-17 08:27 UTC, cloudxxx8 approved these changes
LGTM

2024-04-17 08:28 UTC, cloudxxx8 commented
recheck

2024-04-18 06:58 UTC, cherrycl commented
@dovholuknf Would you please rebase and squash this PR to avoid unknown error for smoke test? Thanks.

2024-04-18 11:51 UTC, dovholuknf commented
@cherrycl i have rebased and squashed

2024-04-19 01:34 UTC, cherrycl commented
@dovholuknf I saw your branch still displayed `1 commit behind edgexfoundry/edgex-compose:main`, would you please rebase main branch again?

2024-04-19 01:53 UTC, dovholuknf commented
@cherrycl -- all set. `This branch is 1 commit ahead of edgexfoundry/edgex-compose:main.`

2024-04-19 05:10 UTC, merged