feat(security): Update compose for adding consul header into Kong's route
edgexfoundry/edgex-compose pull request #73
Opened 2021-04-27 16:15 UTC by jim-wang-intel

- adding env. override for consul's route
- adding volume share between proxy-setup and consul for bootstrap acl token

Closes: #71

Signed-off-by: Jim Wang <yutsung.jim.wang@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## What is the current behavior?

currently there is no consul service route in Kong

## Issue Number: #71 

## What is the new behavior?
added consul service route in Kong through proxy-setup and this depends on `edgex-go` PR https://github.com/edgexfoundry/edgex-go/pull/3391 and enabling Kong's Admin API PR https://github.com/edgexfoundry/edgex-compose/pull/60 in this repo.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

## New Imports
Are there any new imports or modules? If so, what are they used for and why?

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?
In draft mode until other two dependent PRs merged into master
1. edgex-go's adding consul service into kong's route PR: https://github.com/edgexfoundry/edgex-go/pull/3391 
2. edgex-compose's enabling Kong's Admin API PR https://github.com/edgexfoundry/edgex-compose/pull/60 in this repo.

## Other information

2021-04-27 16:22 UTC, bnevis-i submitted a review, later dismissed

2021-04-27 17:58 UTC, lenny-intel requested changes
LGTM, but you still need to run `make build` .

2021-05-05 18:50 UTC, lenny-intel submitted a review, later dismissed
LGTM, need to rebase and take out of draft.

2021-05-05 22:58 UTC, lenny-intel approved these changes
LGTM

2021-05-05 23:06 UTC, jim-wang-intel commented
Tested with the `consul` route (http://localhost:8000/consul/v1/agent/services )   and the following and works:
```sh
jim@jim-NUC7i5DNHE:~/go/src/github.com/edgexfoundry/edgex-compose/compose-builder$ curl -v -H "Authorization: Bearer $JWT_TOKEN" http://localhost:8000/consul/v1/agent/services | jq 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /consul/v1/agent/services HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.47.0
> Accept: */*
> Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjAyNTgxNDksImlhdCI6MTYyMDI1NDU0OSwiaXNzIjoidXVpZGdlbiIsIm5iZiI6MTYyMDI1NDU0OX0.mwZOp4a3kLKuW91ROPcFi2h54WDqAIps9w3wf63809ieR3qLu6HLLNTEMc70RDOIj5949rBc3OxuuaySjFT2zA
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Length: 1644
< Connection: keep-alive
< Vary: Accept-Encoding
< X-Consul-Default-Acl-Policy: deny
< Date: Wed, 05 May 2021 22:43:48 GMT
< X-Kong-Upstream-Latency: 2
< X-Kong-Proxy-Latency: 7
< Via: kong/2.3.2
< 
{ [1644 bytes data]
100  1644  100  1644    0     0   111k      0 --:--:-- --:--:-- --:--:--  114k
* Connection #0 to host localhost left intact
{
  "app-rules-engine": {
    "ID": "app-rules-engine",
    "Service": "app-rules-engine",
    "Tags": [],
    "Meta": {},
    "Port": 48100,
    "Address": "edgex-app-service-configurable-rules",
    "Weights": {
      "Passing": 1,
      "Warning": 1
    },
    "EnableTagOverride": false,
    "Datacenter": "dc1"
  },
  "edgex-core-command": {
    "ID": "edgex-core-command",
    "Service": "edgex-core-command",
    "Tags": [],
    "Meta": {},
    "Port": 48082,
    "Address": "edgex-core-command",
    "Weights": {
      "Passing": 1,
      "Warning": 1
    },
    "EnableTagOverride": false,
    "Datacenter": "dc1"
  },
  "edgex-core-data": {
    "ID": "edgex-core-data",
    "Service": "edgex-core-data",
    "Tags": [],
    "Meta": {},
    "Port": 48080,
    "Address": "edgex-core-data",
    "Weights": {
      "Passing": 1,
      "Warning": 1
    },
    "EnableTagOverride": false,
    "Datacenter": "dc1"
  },
  "edgex-core-metadata": {
    "ID": "edgex-core-metadata",
    "Service": "edgex-core-metadata",
    "Tags": [],
    "Meta": {},
    "Port": 48081,
    "Address": "edgex-core-metadata",
    "Weights": {
      "Passing": 1,
      "Warning": 1
    },
    "EnableTagOverride": false,
    "Datacenter": "dc1"
  },
  "edgex-support-notifications": {
    "ID": "edgex-support-notifications",
    "Service": "edgex-support-notifications",
    "Tags": [],
    "Meta": {},
    "Port": 48060,
    "Address": "edgex-support-notifications",
    "Weights": {
      "Passing": 1,
      "Warning": 1
    },
    "EnableTagOverride": false,
    "Datacenter": "dc1"
  },
  "edgex-support-scheduler": {
    "ID": "edgex-support-scheduler",
    "Service": "edgex-support-scheduler",
    "Tags": [],
    "Meta": {},
    "Port": 48085,
    "Address": "edgex-support-scheduler",
    "Weights": {
      "Passing": 1,
      "Warning": 1
    },
    "EnableTagOverride": false,
    "Datacenter": "dc1"
  },
  "edgex-sys-mgmt-agent": {
    "ID": "edgex-sys-mgmt-agent",
    "Service": "edgex-sys-mgmt-agent",
    "Tags": [],
    "Meta": {},
    "Port": 48090,
    "Address": "edgex-sys-mgmt-agent",
    "Weights": {
      "Passing": 1,
      "Warning": 1
    },
    "EnableTagOverride": false,
    "Datacenter": "dc1"
  }
}
```

2021-05-05 23:30 UTC, bnevis-i approved these changes

2021-05-05 23:32 UTC, merged